<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_event_type extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'event_type' => array(
				'type' => 'VARCHAR',
				'constraint' => 50,
			),
			'event_type_description' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('event_type', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('event_type');
	}
}