<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_events extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'event_title' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'event_description' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'event_type_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'event_from_date' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
			'event_to_date' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
			'created_by' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'created_at' => array(
				'type' => 'TIMESTAMP',
				'constraint' => 0,
			),
			'updated_at' => array(
				'type' => 'TIMESTAMP',
				'constraint' => 0,
			),
			'deleted' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('events', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('events');
	}
}