<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_insurance_company extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'company_name' => array(
				'type' => 'VARCHAR',
				'constraint' => 160,
			),
			'company_main_contact' => array(
				'type' => 'VARCHAR',
				'constraint' => 30,
			),
			'company_alternate_contact' => array(
				'type' => 'VARCHAR',
				'constraint' => 30,
			),
			'company_main_email' => array(
				'type' => 'VARCHAR',
				'constraint' => 150,
			),
			'company_alternate_email' => array(
				'type' => 'VARCHAR',
				'constraint' => 150,
			),
			'company_logo' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'company_logo_thumb' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'created_by' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'created_on' => array(
				'type' => 'TIMESTAMP',
				'constraint' => 0,
			),
			'updated_on' => array(
				'type' => 'TIMESTAMP',
				'constraint' => 0,
			),
			'deleted' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('insurance_company', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('insurance_company');
	}
}