<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_staff extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'uuid' => array(
				'type' => 'VARCHAR',
				'constraint' => 36,
			),
			'staff_firstname' => array(
				'type' => 'VARCHAR',
				'constraint' => 70,
			),
			'staff_lastname' => array(
				'type' => 'VARCHAR',
				'constraint' => 70,
			),
			'staff_othernames' => array(
				'type' => 'VARCHAR',
				'constraint' => 150,
			),
			'staff_emailaddress' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'staff_phonenumber' => array(
				'type' => 'VARCHAR',
				'constraint' => 20,
			),
			'staff_gender' => array(
				'type' => 'VARCHAR',
				'constraint' => 10,
			),
			'staff_user_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'created' => array(
				'type' => 'TIMESTAMP',
				'constraint' => 0,
			),
			'updated' => array(
				'type' => 'TIMESTAMP',
				'constraint' => 0,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('staff', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('staff');
	}
}