<?php namespace Model\Insurance;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Company extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'company_name' => ORM::field('char[160]'),
			'company_main_contact' => ORM::field('char[30]'),
			'company_alternate_contact' => ORM::field('char[30]'),
			'company_main_email' => ORM::field('char[150]'),
			'company_alternate_email' => ORM::field('char[150]'),
			'company_logo' => ORM::field('string'),
			'company_logo_thumb' => ORM::field('string'),
			'created_by' => ORM::field('int[11]'),
			'created_on' => ORM::field('datetime'),
			'updated_on' => ORM::field('datetime'),
			'deleted' => ORM::field('int[11]'),
		);

	}
}