<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Events extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'event_title' => ORM::field('char[255]'),
			'event_description' => ORM::field('string'),
			'event_type_id' => ORM::field('int[11]'),
			'event_from_date' => ORM::field('datetime'),
			'event_to_date' => ORM::field('datetime'),
			'created_by' => ORM::field('int[11]'),
			'created_at' => ORM::field('datetime'),
			'updated_at' => ORM::field('datetime'),
			'deleted' => ORM::field('int[11]'),
		);

	}
}