<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Patients extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'uuid' => ORM::field('char[36]'),
			'patient_first_name' => ORM::field('char[150]'),
			'patient_last_name' => ORM::field('char[150]'),
			'patient_other_names' => ORM::field('char[255]'),
			'patient_phone_number' => ORM::field('char[20]'),
			'patient_email_address' => ORM::field('char[150]'),
			'patient_next_of_kin_name' => ORM::field('string'),
			'patient_next_of_kin_phone' => ORM::field('char[20]'),
			'patient_next_of_kin_email' => ORM::field('char[150]'),
			'patient_next_of_kin_relationship' => ORM::field('char[100]'),
			'patient_insurance_company_id' => ORM::field('int[11]'),
			'patient_insurance_scheme' => ORM::field('string'),
			'patient_created_at' => ORM::field('datetime'),
			'patient_is_active' => ORM::field('int[11]'),
		);

	}
}