<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Staff extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'uuid' => ORM::field('char[36]'),
			'staff_firstname' => ORM::field('char[70]'),
			'staff_lastname' => ORM::field('char[70]'),
			'staff_othernames' => ORM::field('char[150]'),
			'staff_emailaddress' => ORM::field('char[255]'),
			'staff_phonenumber' => ORM::field('char[20]'),
			'staff_gender' => ORM::field('char[10]'),
			'staff_user_id' => ORM::field('int[11]'),
			'created' => ORM::field('datetime'),
			'updated' => ORM::field('datetime'),
		);

	}
}