<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Users extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'uuid' => ORM::field('char[36]'),
			'username' => ORM::field('char[50]'),
			'password' => ORM::field('string'),
			'user_type_id' => ORM::field('int[11]'),
			'user_is_active' => ORM::field('int[11]'),
			'active_hash' => ORM::field('string'),
			'created' => ORM::field('datetime'),
			'updated' => ORM::field('datetime'),
		);

	}
}