<?php namespace Model\User;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Types extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'user_type' => ORM::field('char[70]'),
			'is_active' => ORM::field('int[11]'),
			'created' => ORM::field('datetime'),
			'updated' => ORM::field('datetime'),
		);

	}
}