<?php namespace Model\Event;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Type extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'event_type' => ORM::field('char[50]'),
			'event_type_description' => ORM::field('string'),
		);

	}
}